# frozen_string_literal: true

source "https://rubygems.org"

gemspec
rails_version = (ENV["RAILS_VERSION"] || "6.1.1").to_s

gem "actionview", rails_version
gem "activemodel", rails_version
gem "activesupport", rails_version
gem "railties", rails_version

gem "view_component", path: ENV["VIEW_COMPONENT_PATH"] if ENV["VIEW_COMPONENT_PATH"]