---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
linters:
  ErbSafety:
    enabled: true
  FinalNewline:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
