---
EnableDefaultLinters: true
exclude:
  - '**/vendor/**/*'
  - 'test/sandbox/app/components/content_security_policy_nonce_component.html.erb'
linters:
  ErbSafety:
    enabled: true
  FinalNewline:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      inherit_from:
        - .rubocop.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
