inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails_edge.yml

AllCops:
  SuggestExtensions: false
  Exclude:
    - test/tmp/**/*
    - vendor/bundle/**/*

Gemspec/OrderedDependencies:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
