inherit_gem:
  rubocop-github:
    - config/default.yml
    - config/rails_edge.yml

AllCops:
  SuggestExtensions: false
  Exclude:
    - gemfiles/**/*
    - test/tmp/**/*
    - vendor/bundle/**/*

Gemspec/OrderedDependencies:
  Enabled: true

Layout:
  Enabled: true

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Max: 120
  Enabled: true

Layout/SpaceBeforeBrackets:
  Enabled: true
