#!/usr/bin/env bash

# Publish gem
# this step has been replaced by .github/workflows/push_gem.yml

# Publish updated docs
git branch -D gh-pages
git checkout -b gh-pages main
git push origin gh-pages --force
git checkout main
