#!/usr/bin/env bash

# Update version info in data
version=$(ruby ./lib/view_component/version.rb)
echo "version: $version" >> docs/_data/library.yml

# Publish gem
bundle exec rake release

# Publish updated docs
git branch -D gh-pages
git checkout -b gh-pages main
git push origin gh-pages --force
git checkout main
