#!/usr/bin/env bash

read -p "MAJOR: " major
read -p "MINOR: " minor
read -p "PATCH: " patch

# creating branch
git checkout -b release-v$major.$minor.$patch

# updating version file
sed -E -i.bak \
    -e "s/MAJOR = [0-9]+/MAJOR = $major/g" \
    -e "s/MINOR = [0-9]+/MINOR = $minor/g" \
    -e "s/PATCH = [0-9]+/PATCH = $patch/g" \
    lib/view_component/version.rb

# updating changelog
sed -i.bak "/## main/ {a\
\\
\\
## $major.$minor.$patch
}" CHANGELOG.md

# removing bak files
rm CHANGELOG.md.bak
rm lib/view_component/version.rb.bak

# updating Gemfile.lock
bundle

# commiting and pushing
git add CHANGELOG.md Gemfile.lock lib/view_component/version.rb
git commit -m "release v$major.$minor.$patch"
git push origin release-v$major.$minor.$patch

echo "####################################################"
echo "Now, open a PR with this branch and merge it to main"
echo "Then, run bundle exec rake release on main to release the gem to RubyGems"
echo "Finally, create a GitHub release https://github.com/github/view_component/releases/new with the changes from CHANGELOG"
echo "####################################################"
