#!/bin/bash
# Exit if repo already exists
# Ensure that when we install view_component in the repo, we install this copy.
bundle config local.view_component $(pwd)
# Create and enter a minimal example repo
rails new --minimal replicate-bug
cd replicate-bug
# Add our local copy of ViewComponent
bundle add --git https://github.com/github/view_component --branch main
# Generate a controller
rails g controller Home index
# Generate ApplicationComponent, assuming most folks use it.
rails g component ApplicationComponent --template_engine=no_template
# Root to the index action on HomeController
cat << 'ROUTES' > 'config/routes.rb'
Rails.application.routes.draw do
  root to: 'home#index'
end
ROUTES