name: Update Changelog

on:
  pull_request:
    types: [ closed ]

jobs:
  changelog:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.6'
      - run: go get -u github.com/git-chglog/git-chglog/cmd/git-chglog
      - run: git-chglog --output docs/CHANGELOG.md
