name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: ["5.2.3", "6.0.0.rc2", "master"]
        ruby_version: ["2.5.0", "2.6.0"]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        version: ${{ matrix.ruby_version }}
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle update
        bundle install --jobs 4 --retry 3
        bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
